version: '3.1'

services:
  monitor_api:
    restart: always
    image: 11.11.10.33:5000/monitor:1.2.1
    container_name: monitor_api
    environment:
      - SERVICE=api
      - IP=0.0.0.0
      - API_PORT=12306
    volumes:
      - /p300/xiaolong/SmartSystem/NodeMonitor/monitorDB:/app/db
    network_mode: host

  monitor_server:
    restart: always
    image: 11.11.10.33:5000/monitor:1.2.1
    container_name: monitor_server
    environment:
      - SERVICE=server
      - IP=0.0.0.0
      - SOCKET_PORT=12307
    volumes:
      - /p300/xiaolong/SmartSystem/NodeMonitor/monitorDB:/app/db
    network_mode: host

  monitor_usage:
    restart: always
    image: 11.11.10.33:5000/monitor:1.2.1
    container_name: monitor_usage
    environment:
      - SERVICE=usage
      - DISKS=/hracond2:/hracond2:/hracond3:/gsainsdc2:/p300:/gsapub:/hracond:/upload:/gsapub3:/gsainsdc3:/hracond4:/hraupload
    volumes:
      - /proc:/host_proc:ro
      - /path/to/monitorDB:/app/db
      - /hracond2:/hracond2:ro
      - /gsapub2:/gsapub2:ro
      - /hracond3:/hracond3:ro
      - /gsainsdc2:/gsainsdc2:ro
      - /p300:/p300:ro
      - /gsapub:/gsapub:ro
      - /hracond:/hracond:ro
      - /upload:/upload:ro
      - /gsapub3:/gsapub3:ro
      - /gsainsdc3:/gsainsdc3:ro
      - /hracond4:/hracond4:ro
      - /hraupload:/hraupload:ro
    network_mode: host